### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by jldugger** [osuosl/website-issues#9]
If you try to search, you get some errors, and no search results!

Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in osu_search_search() (line 355 of /var/www/osuosl.org/drupal7-osuosl.org/acquia-drupal-7/sites/all/modules/osu_search/osu_search.module).

Warning: file_get_contents(http://search.oregonstate.edu/?of=xml&q=sour+site%3Ahttp%3A%2F%2Fosuosl.org&start=): failed to open stream: no suitable wrapper could be found in osu_search_search() (line 355 of /var/www/osuosl.org/drupal7-osuosl.org/acquia-drupal-7/sites/all/modules/osu_search/osu_search.module).

**Comment by ramereth** [comment]
This should be a simple vhost change I think to allow this php option.

**Comment by nobane** [comment]
The search bar has been disabled, thus solving this issue.
